//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSPredicacionPorTelefono
{
    using System;
    using System.Collections.Generic;
    
    public partial class Territorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Territorio()
        {
            this.Casas = new HashSet<Casa>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CongregacionId { get; set; }
        public string Territorio1 { get; set; }
        public string Mapa { get; set; }
        public Nullable<decimal> CoordenadaX { get; set; }
        public Nullable<decimal> CoordenadaY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Casa> Casas { get; set; }
        public virtual Congragacion Congragacion { get; set; }
    }
}
