//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredicacionPorTelefono.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casa
    {
        public int Id { get; set; }
        public int TerritorioId { get; set; }
        public string Tipo { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public string DepInt { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Telefono3 { get; set; }
        public string Abonado { get; set; }
        public string Distrito { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Territorio Territorio { get; set; }
    }
}
